name: Docker Hub Image CI

on:
  push:
    branches:
      - trunk

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ vars.DOCKER_USERNAME }}/speek:latest
        # For tagging with the Git commit SHA, add this:
        # tags: ${{ secrets.DOCKER_USERNAME }}/speek-app:latest,${{ secrets.DOCKER_USERNAME }}/speek-app:${{ github.sha }}

